import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "iElectricalDevices",
  description: "Generated by Celso Gabriel Prado",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <div className="justify-items-center min-h-screen gap-16 font-[family-name:var(--font-poppins)]">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
